name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  check_schema:
    name: Check Schema with Apollo Studio
    if: false
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      # rename this to a valid subgraph name
      SUBGRAPH_NAME: foo-bar
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Generate Schema
        run: dotnet run --project Server -- schema export --output ../schema.graphql
      - name: Schema Check
        run: rover subgraph check ${{ secrets.APOLLO_GRAPH_REF }} --schema schema.graphqls --name ${{ env.SUBGRAPH_NAME }}
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
